### ISSUE TITLE
クレジットカードの登録が出来ない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#54]
正しいクレジットカードを入れているのに登録が出来ない
![2017-04-16 00 07 59](https://cloud.githubusercontent.com/assets/17405609/25064618/dcd60d92-2238-11e7-8b30-53af57213535.png)

**Comment by tomoyuki1110** [comment]
月曜日に本番環境に変更

**Comment by alexeypolitov** [comment]
@tomoyuki1110 本番に切りけましたのでご確認ください
