### ISSUE TITLE
使い方の説明を動画で

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#61]
最初に入った時に、

１．サイトの登録方法
２．登録したサイトのタグを取得方法
３．ユーザの追加方法・削除方法
４．自動返信機能（スタンダードなものだけ）

上記４つを動画にしてインストラクションをいれてください。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 内容を教えてください
