### ISSUE TITLE
iphone7で自分で打った文字がみれなくなる。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#65]
スクショ添付しておきます。
![2017-05-07 12 37 16](https://cloud.githubusercontent.com/assets/17405609/25777760/18fa3556-3322-11e7-9ef9-9c87529baa63.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。Widgetコードを更新して、キャッシュを空にして、ご確認ください
