### ISSUE TITLE
当該URL以外もバブルが出るように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#66]
https://jk.dinate.jp/

現在だと
https://jk.dinate.jp/

**Comment by tomoyuki1110** [comment]
のように指定したところしか自動メッセージが出てこない設定になっているが、
タグを入れた全部にもでるような設定ができるようにしてほしい。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 こちらでどの問題ですか？現在だと
「https://jk.dinate.jp」でも「https://jk.dinate.jp/」でも対応してますので

**Comment by tomoyuki1110** [comment]
例えば、

jk.dinate.jp/aaa  /bbb /ccc 全部でてきますか？

URLが違うと出てこなかったきがしています。
