### ISSUE TITLE
アクションを削除できない。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#67]
![2017-05-07 13 13 13](https://cloud.githubusercontent.com/assets/17405609/25777875/f229f9e8-3326-11e7-869e-13a787d33768.png)

間違えて追加ボタンをおした時にアクションの削除が出来ない

**Comment by alexeypolitov** [comment]
@tomoyuki1110 確認しましたができるようです。

<img width="723" alt="screen shot 2017-05-08 at 9 58 49" src="https://cloud.githubusercontent.com/assets/3468058/25786744/07876434-33d5-11e7-85a2-cc9dece4b0ab.png">

**Comment by tomoyuki1110** [comment]
めっちゃ見えづらいのでもう少し濃くしてもらえますか？

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。Widgetコードを更新して、キャッシュを空にして、ご確認ください
