### ISSUE TITLE
紹介文を入れているのに紹介文が入ってこない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#68]
![2017-05-07 18 20 49](https://cloud.githubusercontent.com/assets/17405609/25779406/f5014de4-3351-11e7-8eb6-e8e6d01ea3ce.png)
![2017-05-07 18 22 18](https://cloud.githubusercontent.com/assets/17405609/25779411/1b130b76-3352-11e7-9fd5-635add81fbe3.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 こちらに入ってます。
<img width="375" alt="screen shot 2017-05-08 at 10 00 24" src="https://cloud.githubusercontent.com/assets/3468058/25786756/3b7977fa-33d5-11e7-8106-98f69ab982fb.png">

**Comment by tomoyuki1110** [comment]
こちらですが、もう一つ、チャット側にも挨拶文を入れるようにつくってもらえますか？

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。Widgetコードを更新して、キャッシュを空にして、ご確認ください
