### ISSUE TITLE
自動返信オペレーターのプロフィールが白紙

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#69]
どうやって設定しますか
設定場所も見つからずです。
![2017-05-07 18 23 20](https://cloud.githubusercontent.com/assets/17405609/25779415/40d2614a-3352-11e7-9a1f-6334dc82421f.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 プロフィールは設定できないです。アイコンだけデザインのところでアップできます。
