### ISSUE TITLE
chat用アイコンと管理者アイコンが混同する？

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-sdk-web#71]
何故かたまに混同します

管理者のアイコンになった時は、名前がうさぎとでます、
![2017-05-07 18 27 17](https://cloud.githubusercontent.com/assets/17405609/25779435/ccfd75e2-3352-11e7-9215-89046cb03ebe.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 チャットのアイコンは自動返信のアイコンとなってます
